name: LiarBar
main: cn.pianzi.liarbar.paperplugin.bootstrap.LiarBarPaperPlugin
version: 1.0.0-SNAPSHOT
api-version: '1.21'
authors: [Pianzi]
softdepend: [Vault, packetevents]
libraries:
  - com.h2database:h2:2.3.232
  - org.mariadb.jdbc:mariadb-java-client:3.5.3
  - com.zaxxer:HikariCP:6.2.1
commands:
  liarbar:
    description: Liar's Bar gameplay command
    usage: /liarbar <mode|join|play|challenge|stop|status|stats|top|season|reload|help>
    aliases: [lb]
permissions:
  liarbar.use:
    description: Access player gameplay commands
    default: true
  liarbar.admin:
    description: Access admin commands
    default: op
